# Generated by Django 2.1.4 on 2019-11-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181219_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='valid_period',
            field=models.SmallIntegerField(choices=[(1, '1天'), (3, '3天'), (7, '1周'), (14, '2周'), (30, '1个月'), (60, '2个月'), (90, '3个月'), (120, '4个月'), (180, '6个月'), (360, '12个月'), (540, '18个月'), (720, '24个月')]),
        ),
    ]
